adjective= input('enter an adjective: ')
print(adjective)
animal= input('type a name of animal: ')
print(animal)
verb1= input('enter a verb: ')
print(verb1)
exclamation= input('enter an exclamation: ')
print(exclamation)
verb2= input('enter a verb: ')
print(verb2)
verb3= input('enter a verb: ')
print(verb3)
output= f'The other day, I was really in trouble. It all started when I saw a very \n{adjective} {animal} {verb1} down the hallway. "{exclamation.capitalize()}!" I yelled. But all \nI could think to do was to {verb2} over and over. Miraculously,\nthat caused it to stop, but not before it tried to {verb3} \nright in front of my family.'
print(output)